language: go

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install btrfs-tools libdevmapper-dev libgpgme11-dev libapparmor-dev libseccomp-dev
  - sudo apt-get -qq install autoconf automake bison e2fslibs-dev libfuse-dev libtool liblzma-dev gettext

install:
  - make install.tools

before_script:
  - export PATH=$HOME/gopath/bin:$PATH
  - export LD_LIBRARY_PATH=/usr/local/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

env:
    global:
        - TRAVIS=1

jobs:
  include:
    - stage: Build and Verify
      script:
        - make gofmt
        - make lint
        - make testunit
        - make docs
        - make
      go: 1.8.x
    - stage: Build and Verify
      script:
        - make gofmt
        - make lint
        - make testunit
        - make docs
        - make
      go: 1.9.x
    - stage: Integration Test
      script:
        - make all
        - make integration
      go: 1.8.x

# Turn off notifications until we have our own channel (After rename)
# notifications:
#  irc: "chat.freenode.net#cri-o"
