name: "FOSSA Scan"
on:
- pull_request_target

jobs:
  fossa-scan:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: fossa
        name: FOSSA Scan
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze --experimental-force-first-party-scans && fossa test --diff "${{ github.event.pull_request.base.sha }}" && fossa report attribution --format text
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"

